### ISSUE TITLE
File structure

### ISSUE THREAD

**Issue by iPhatty** [fac-14/Team-Rocket-PokeGIF#27]
For a good developer's experience you may want to think about sorting the files in specific folders. They are all currently in the root and can be difficult to look at when file numbers start to increase. Think about how you could sort them into folders to make it much easier to look at next time 😎

What I like to do is put the logic related files in a 'src' folder and the front end files i.e index.html and DOM.js in a 'public' folder

**Comment by Parissai** [comment]
I second @iPhatty. But we will cover this in detail next week in modularisation challenge. So don't be worried too much about it.

**Comment by thejoefriel** [comment]
Thanks. Makes sense. If we get a chance we'll try to tidy it today - would be good to start getting used to best practice.
