### ISSUE TITLE
Next Gif

### ISSUE THREAD

**Issue by Zeanort** [fac-14/Team-Rocket-PokeGIF#29]
The next gif button could be made to only appear when a pokemon has been searched or randomly picked.

**Comment by iPhatty** [comment]
This is because you do not have an else statement to tell your gifCallback what to do otherwise 😎👍

**Comment by martingaston** [comment]
This is a bit of a hack but we've now got a pokeball overlay which covers the need for this - but we would look to incorporate an else statement in a refactoring push. Thanks :smile:
