### ISSUE TITLE
looks a bit off on the mobile.. 

### ISSUE THREAD

**Issue by Brymon** [fac-14/Team-Rocket-PokeGIF#38]
![screen shot 2018-07-20 at 10 39 59](https://user-images.githubusercontent.com/26569161/42995672-54f24aee-8c09-11e8-8975-d02d170fc6cb.png)
![screen shot 2018-07-20 at 10 40 17](https://user-images.githubusercontent.com/26569161/42995677-56bd0bd4-8c09-11e8-96af-c0f2ac3ee791.png)

this is how it displays on galaxy S5 both horizontal and vertical position.. 
also :
the images stretch way too much on desktop view as well in my opinion, ending up being very pixelated...

**Comment by arrested-developer** [comment]
Is this on Chrome? We can't recreate this issue, it looks fine on mobile to me...
